-   id: alembic-autogen-check
    name: alembic-autogen-check
    description: 'check that alembic migrations are in sync with SQLAlchemy models'
    entry: alembic-autogen-check
    language: python
    language_version: python3
    pass_filenames: false
